// <auto-generated />
using CRUD_ASP.POSTGRESQL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRUD_ASP.POSTGRESQL.Entities
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240214105854_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRUD_ASP.POSTGRESQL.Entities.TblBarang", b =>
                {
                    b.Property<int>("IdBarang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_barang")
                        .HasDefaultValueSql("nextval('tbl_baranf_id_barang_seq'::regclass)");

                    b.Property<string>("KategoriBarang")
                        .HasColumnType("text")
                        .HasColumnName("kategori_barang");

                    b.Property<string>("NamaBarang")
                        .HasColumnType("text")
                        .HasColumnName("nama_barang");

                    b.HasKey("IdBarang")
                        .HasName("tbl_baranf_pkey");

                    b.ToTable("tbl_barang", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
